name: Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [12.x]
    steps:     
    - name: Install Packages
      run: npm install --no-package-lock
    - name: Run on server
      run: node server.js
